print("Mad Libs")
print("Our School Cafeteria Has really ADJECTIVE Food, Thinking About It Makes Me VERB. The Food Tastes Like NOUN.")
Adj = input("Enter an adjective")
Verb = input("Enter a Verb")
Noun = input("Enter a Noun")
print(f"Our School Cafeteria Has really {Adj} Food, Thinking About It Makes Me {Verb}. The Food Tastes Like {Noun}.")
